### ISSUE TITLE
Intersection with rotated rectangle

### ISSUE THREAD

**Issue by marcospassos** [thelonious/kld-intersections#11]
First of all, thanks for sharing this amazing library!

Is there support for computing the intersection with a rotated rectangle?

**Comment by thelonious** [comment]
There isn't direct support for rotated rectangles, but with a little work, you can get what you need. You need to do something like the following:

- Convert the corners of the unrotated rectangle to a polygon
- Rotate each point in the polygon
- Use any of the intersect*Polygon functions

I can provide an example, if you need it.

Looking at the master branch, I'm only exposing Point2D, but you also need Matrix2D for the rotation, so you'll need to pull in kld-affine@0.1.0 unfortunately. I'll fix that in a future release.

**Comment by marcospassos** [comment]
@thelonious thanks for your quick reply, however, I think I need further assistance.

To give you a context, I would like to compute the intersection between a line and a diamond. I can get a diamond by flipping a square by 45deg, this is why I asked about how to compute the intersection using a rotated shape. Perhaps there is an easier way to accomplish it. If it is a good option, I believe that Matrix2D can help here, right?

* Currently, I'm marking Matrix2D as a dependency, but exposing it is the right way IMHO to go.

**Comment by thelonious** [comment]
I've added [an example](https://github.com/thelonious/kld-intersections/blob/development/examples/rotate-rectangle-line.js) to the development branch.

FWIW, the development branch exposes Matrix2D now. I have not updated the module on npm yet, however.

**Comment by thelonious** [comment]
FYI, I pushed kld-intersections@0.2.0 which exposes Matrix2D

**Comment by marcospassos** [comment]
Nice job, @thelonious! Thank you very much again!
