### ISSUE TITLE
The latest version is broken 

### ISSUE THREAD

**Issue by marcospassos** [thelonious/kld-intersections#15]
I'm getting the following error using the latest version:

```
Cannot read property 'concat' of undefined
```

This is the related code:
```js
var method;
var args;

if ( shape1.name < shape2.name ) {
    method = "intersect" + shape1.name + shape2.name;
    args = shape1.params.concat( shape2.args );
}
else {
    method = "intersect" + shape2.name + shape1.name;
    args = shape2.params.concat( shape1.args );
}

if ( !(method in Intersection) ) {
    throw new Error("Intersection not available: " + method);
}

result = Intersection[method].apply(null, args);
```

It's probably happening because `IntersectionArgs` has no property named `params`.

**Comment by thelonious** [comment]
Thanks @marcospassos! I thought I had pushed that fix already. Regardless, v0.3.1 is up with those fixes in it. Obviously, I need unit tests, which is one of the main reasons this library isn't at 1.0 :)

**Comment by marcospassos** [comment]
Thanks, @thelonious.

BTW, do you have any plans of adding unit tests to the library anytime soon? Our intention is to use this amazing library in the production environment, so some tests are fundamental.

**Comment by thelonious** [comment]
I want to get a first round done soon, but I can't given a ETA on that. If you're concerned about stability, then you might want to look at @Quazistax's [fork](https://github.com/Quazistax/kld-intersections). I know he spent a good amount of time troubleshooting problem cases. I'm in the process of incorporating his work, but, again, at this time I can't say when that will be complete.

**Comment by marcospassos** [comment]
@thelonious good to know! We'll keep using your this original version.

About the tests, I'll try to help you with the job providing tests according to our use case.
