### ISSUE TITLE
No Intersections for intersectBezier3Bezier3 Edge Case

### ISSUE THREAD

**Issue by Shkyrockett** [thelonious/kld-intersections#17]
Hi, while porting your code to c# and writing test cases, I ran across this weird little edge case to Intersection.intersectBezier3Bezier3 that I thought you might be interested in.

Here is the geometry in svg form:
```
<svg xmlns="http://www.w3.org/2000/svg">
    <path gui:edit="editable" d="M150,150 C183.33333333333331,216.66666666666663 233.33333333333337,216.66666666666663 300,150" stroke="blue" stroke-width="5" fill="none"/>
    <path gui:edit="editable" d="M100,200 C166.66666666666663,133.33333333333337 233.33333333333337,133.33333333333337 300,200" stroke="orange" stroke-width="5" fill="none"/>
</svg>
```

Here are the current results:

![nointersection](https://user-images.githubusercontent.com/16521931/29155806-195f23be-7d53-11e7-9f34-9f509b00fea4.png)

**Comment by thelonious** [comment]
Thanks for this. I was able to recreate the issue with the latest code here. If this is a show stopper for you, then you may want to consider the approach used in [this example](https://github.com/thelonious/kld-intersections/blob/development/examples/tessellate-cubic-beziers.js).

**Comment by thelonious** [comment]
@Shkyrockett I was able to hunt down the issue that was causing this to fail. I've pushed a 0.4.1 release to npm. I'm going to go ahead and close this. Please re-open if you're still seeing issues. Thanks!

**Comment by Shkyrockett** [comment]
@thelonious Nice work!
