### ISSUE TITLE
Usage of Vector instead of Vector2D in IntersectionQuery.js

### ISSUE THREAD

**Issue by Krzysztof-FF** [thelonious/kld-intersections#21]
Maybe I'm missing something, but shouldn't the line #24 in kld-intersections/lib/IntersectionQuery.js
`    var v = Vector.fromPoints(center, point);`
read
`    var v = Vector2D.fromPoints(center, point);`
??

**Comment by thelonious** [comment]
Thanks @Krzysztof-FF! I've pushed that change to development. I'm not sure when I'll push a next release.
