### ISSUE TITLE
Use library in pure javascript

### ISSUE THREAD

**Issue by adel-tahir** [thelonious/kld-intersections#22]
How can I use this library in the client-side pure javascript?

Is there any distributed version?

**Comment by thelonious** [comment]
@adel-tahir You should be able to use a tool like [webpack](https://webpack.js.org/) or [browserify ](http://browserify.org/) to package this module and all dependencies for use in the browser. Is that what you are looking for?

**Comment by adel-tahir** [comment]
@thelonious Thanks!
