### ISSUE TITLE
Problem with intersectBezier2Polygon

### ISSUE THREAD

**Issue by AndreaSimeone** [thelonious/kld-intersections#23]
Hello thelonious,
I'm trying to obtain the intersection between quadratic bezier and a polygon but I'm stuck with this error:
![schermata 2018-02-07 alle 13 12 12](https://user-images.githubusercontent.com/17427513/35915807-945a3f74-0c08-11e8-9784-099ae6b490c7.png)
where this.intersectBezier2Polyline isn't a function.
Inspecting your code I found that intersectBezier2Polygon is amenable to intersectBezier2Polyline like intersectBezier2Circle is a particular case of intersectBezier2Ellipse (with rx e ry = r) but the two functions differ:

`Intersection.intersectBezier2Circle = function(p1, p2, p3, c, r) {
	    return Intersection.intersectBezier2Ellipse(p1, p2, p3, c, r, r);`

`Intersection.intersectBezier2Polygon = function(p1, p2, p3, points) {
	    return this.intersectBezier2Polyline(p1, p2, p3, closePolygon(points));
	};`

Modifying the second all seems to work fine:
`Intersection.intersectBezier2Polygon = function(p1, p2, p3, points) {
	    return Intersection.intersectBezier2Polyline(p1, p2, p3, closePolygon(points));
	};`
Here's a pic of my working example:
![schermata 2018-02-07 alle 15 25 35](https://user-images.githubusercontent.com/17427513/35921552-38459fb8-0c1b-11e8-99bd-e32d3d1347d0.png)

**Comment by thelonious** [comment]
Hi @AndreaSimeone,

Thanks for the heads up! I’ll make these changes and push out a new version as soon as I can.

**Comment by thelonious** [comment]
I pushed this fix to development. I'll try to push out a new version this weekend.
