### ISSUE TITLE
Get Bezier T value for point

### ISSUE THREAD

**Issue by danmarshall** [thelonious/kld-intersections#25]
Hi Kevin,
This is an awesome library! I don't have an issue but this is more of a question:
I know I can get the intersection points on a Bezier curve. Do you have a function to get the T values of said points?

Thanks,
Dan

**Comment by thelonious** [comment]
Hi Dan,

Thanks for the kind words :)

I don't have function for what you need, but that would indeed be very handy, for example, if you wanted to split the curve at the intersection point. I do use `t` to calculate the intersection point, but that's for the second curve only and it's not exposed currently. I could change that.

Alternately, it might not be too ugly to write a function where given a point, you get back `t`. Lets say you're working with a cubic bezier. You can convert the x coordinates of your points to a cubic (see Bernstein polynomial), subtract the intersection point's x value, then solve for `t`. Now use those `t` values in the y coordinate polynomial and check if the resulting y value is close to your intersection point value. You would need to do this for both curves.

HTH,
Kevin

**Comment by danmarshall** [comment]
Great, thank you!
