### ISSUE TITLE
Rotated ellipse intersection with line

### ISSUE THREAD

**Issue by vigalo** [thelonious/kld-intersections#26]
Hello : 

It is possible to calculate the intersections points of a line with a rotated ellipse?

If yes, how can I do it?

Thanks

**Comment by thelonious** [comment]
@vigalo The current codebase doesn't support that directly. However, off of the top of my head, I think you could do something creative where you apply the ellipse's rotation to the line, find the intersection points, then rotate those points back into the original domain. I believe @Quazistax implemented something similar to this in [his fork](https://github.com/Quazistax/kld-intersections). If you need it, I might be able to whip up an example over the weekend.

**Comment by thelonious** [comment]
@vigalo I've added an example of what was describing on the development branch. The code is here:

[rotated-ellipse-line.js](https://github.com/thelonious/kld-intersections/blob/development/examples/rotated-ellipse-line.js)

And the output it creates is here:

[rotated-ellipse-line.svg](https://github.com/thelonious/kld-intersections/blob/development/examples/rotated-ellipse-line.svg)

HTH,
Kevin

**Comment by vigalo** [comment]
Thank you, #thelonious.
That solved my problem!!
