### ISSUE TITLE
Fix Typos in examples/PathHandler.js

### ISSUE THREAD

**Issue by jdthorpe** [thelonious/kld-intersections#28]
`this.shapes - 1` should be replaced with `this.shapes.length - 1` [here](https://github.com/thelonious/kld-intersections/blob/development/examples/PathHandler.js#L274), [here](https://github.com/thelonious/kld-intersections/blob/development/examples/PathHandler.js#L307), [here](https://github.com/thelonious/kld-intersections/blob/development/examples/PathHandler.js#L338)
 and [here](https://github.com/thelonious/kld-intersections/blob/development/examples/PathHandler.js#L369).

**Comment by thelonious** [comment]
Fixed and pushed. Thanks for pointing that out. Of course, if I followed good programming practices I would at least have sanity unit tests for that :)
