### ISSUE TITLE
intersectBezier2Ellipse when the bezier is nearly a line

### ISSUE THREAD

**Issue by gontard** [thelonious/kld-intersections#3]
I found an issue when the bezier 2 is close to a line:

```
Intersection.intersectBezier2Ellipse(new Point2D(599.6212158203125, 399.6212158203125),
            new Point2D(749.8636506539298, 399.60549803175195),
            new Point2D(900.1052551269531, 400.1052551269531),
            new Point2D(740.8397695373246, 399.72029570133856),
            3.375, 3.375)
```

The found intersections are:

```
new Point2D(756.1673452777627, 399.74474836394853)
new Point2D(725.5121897521101, 399.69852555069036)
```

These are not points of the ellipse.

Any ideas ?

**Comment by Quazistax** [comment]
As much as I tested, problem disappears when using Jenkins-Troub polynomial root finding. 

https://github.com/Quazistax/kld-polynomial/tree/rpoly-root-finding

Let me know if you encounter other problems.

**Comment by thelonious** [comment]
@Quazistax: this is encouraging! I thought these issues might have been occurring in the calculation of the bézout

**Comment by thelonious** [comment]
That's encouraging

**Comment by Quazistax** [comment]
I'm working on a page (currently at [www.quazistax.com](http://www.quazistax.com)) for purpose of testing some javascript libraries related to SVG. It's not much, but you can see the difference when changing some parameters and algorithms.

I implemented modified newton's method for quartic polynomial (development not complete). It looks as good as rpoly for now (in terms of accuracy, probably not in terms of speed).

I'll put some source on GitHub when I find time to arrange it.

**Comment by Quazistax** [comment]
I'm using combination of newton/secant/bisection now for quartic polynomial root finding. I also made some other changes. It is possible to intersect rotated/scaled/skewed shapes now. There are a few examples on my page.

Code changed quite a lot as i was having fun with it, should I create pull request with all that changes? Maybe if you create new development branch I could create pull request towards that branch, and you can decide what an how to merge to master later. That goes for kld-polynomial too.

I tested it in browsers (Firefox/Chrome/IE11) as much I was able. I was not developing under node.js so I can not say how it behaves there, but it works ok in Chrome.

**Comment by thelonious** [comment]
@quazistax, I'm traveling and won't be able to look at this until tomorrow. I'll setup a development branch as soon as I can and I'll comment here once once that has been pushed.

**Comment by thelonious** [comment]
@Quazistax: development branches have been created here and in kld-polynomial. Those are now the defaults (on github) in each repo as well
