### ISSUE TITLE
IntersectionQuery.pointInCircle: Vector2D is not imported into module

### ISSUE THREAD

**Issue by levgaas** [thelonious/kld-intersections#30]
Vector2D produces error since it's not imported and thus undefined

**Comment by thelonious** [comment]
@levgaas Thanks for the heads up. One of these days, I will write unit tests :)

**Comment by levgaas** [comment]
Thanks for the quick update. I know I could have make PR myself. But I was too overwhelmed with geometry and stuff =)

Thanks for the lib. Also I found that path intersection doesn't work as expected. I'll try to elaborate later on
