### ISSUE TITLE
Example or suggestions regarding viewBox?

### ISSUE THREAD

**Issue by ajbogh** [thelonious/kld-intersections#31]
I have a polyline shape using the code below:

    <symbol viewBox="0 0 88 72" id="poly">
        <path d="M 0 36 18 0 70 0 88 36 70 72 18 72Z"></path>
    </symbol>

The symbol is defined in the <defs> section of the SVG, and used by using the <use> element.

Is there any way that the poly() function can be given the viewBox property to adjust the intersection point?

**Comment by thelonious** [comment]
I'll have to refresh myself with all of the transforms involved with symbols. I do have code to convert a view box to a transformation matrix. There may be additional transformations that have to be applied. Once we have that matrix, we can apply it to the points in the path (your polygon) and then intersect from there. I hope to have something for you soon

**Comment by ajbogh** [comment]
Thanks @thelonious! I look forward to seeing an example using a parent SVG with <use> statements and viewboxes. I know that it's difficult and kind of a weird use case. 

As a workaround I've found that forcing my users to define a width and height on the symbol which matches the maximum width and height of the element inside the viewbox is the best option, basically making the image fill the viewbox 100%. 

Instead of a width like "154" and a viewbox of "88" with an element maximum width of "88", the width of the symbol should also be "88", then the library works perfectly.

**Comment by thelonious** [comment]
@ajbogh Would you by any chance have a minimal example of what you're looking for, assuming this is still something you're interested in?

**Comment by ajbogh** [comment]
@thelonious I created a Github project that shows an example. I decided that a GH project would be the best method as you could run the code and modify it as you would any other project. Instructions are included in the README.md.

https://github.com/ajbogh/kld-intersections-issue-31

**Comment by thelonious** [comment]
This is awesome! I'll have a look and see what I can figure out. Thanks!

**Comment by thelonious** [comment]
I've just setup a pull request with some changes that appear to be working. Let me know if that was what you were looking for.

Thanks again!

**Comment by ajbogh** [comment]
Thanks @thelonious. If I get some time I'll throw together an example with this. It might be useful to include the ViewBox.js and new PathHandler.js files in the project, but probably with options that allow backwards compatibility. I'll see what I can add to your project for this.

**Comment by thelonious** [comment]
I'm sure ViewBox and the updated sample can be improved upon. Shouldn't have to change any code that uses the updated PathHandler. You don't have to pass in a Matrix2D which preserves the constructor signature. In that case, it will generate an identify matrix internally, giving you the same results as the previous version of that class.

I'd like to include ViewBox and PathHandler in some other module. It doesn't really make sense to have them in this module, although I probably could argue that ViewBox could live here.
