### ISSUE TITLE
Another Case of no intersections for intersectBezier3Bezier3 Edge Case

### ISSUE THREAD

**Issue by Shkyrockett** [thelonious/kld-intersections#35]
Hi, I ran across another weird intersection edge case for intersectBezier3Bezier3 that I thought you might be interested in.

![Edge case](https://user-images.githubusercontent.com/16521931/57174495-d8e75d80-6df4-11e9-9541-36f2c762d09f.PNG)

Here are the curves:

    <path d="M150,150 C183.33333333333331,216.66666666666663 233.33333333333337,216.66666666666663 300,150"/>
    <path d="M100,200 C166.66666666666663,133.33333333333337 233.33333333333337,133.33333333333337 300,200"/>

**Comment by thelonious** [comment]
Thanks for the heads up! It's interesting how multiples of 1/3 cause issues.

**Comment by thelonious** [comment]
Looks like I've already resolved this exact case:

> https://github.com/thelonious/kld-intersections/blob/master/test/cubic-cubic-fail.js

When I run that example, I get the following SVG image:

![image](https://user-images.githubusercontent.com/34288/57181982-0bbe3f80-6e4f-11e9-9661-7397d1bc5862.png)

And that has these intersections:

```svg
<circle cx="155.388" cy="159.951" r="2" stroke="red" fill="none"/>
<circle cx="271.264" cy="175.393" r="2" stroke="red" fill="none"/>
```

Maybe you're running an older version of the library? I tested with 0.4.3.
