### ISSUE TITLE
Questions about some logs

### ISSUE THREAD

**Issue by zowiegong** [thelonious/kld-intersections#42]
Hi~
I don't know what the specific effect of these two lines of code is.
But when I call it multiple times, the log is full of my screen.
Maybe I can submit PR to delete them?

https://github.com/thelonious/kld-intersections/blob/32254ef7f904472f6a8b2c21b64a4973d28c8c3e/lib/Intersection.js#L97-L98

**Comment by thelonious** [comment]
Hi @zowiegong,

I just added arc support in the last release and that was some debugging code that I missed taking out. I will be pushing a new release soon (hopefully today) and I will take care of that. Looks like I need to have linting complain about those!

Thanks for the heads up and my apologies for the garbage output.

**Comment by thelonious** [comment]
I've made the fix on [this commit](https://github.com/thelonious/kld-intersections/commit/9be6f85c438ab42ab5718b3711c1543a9c7006a7) in case you want to run from the development branch. Either way, I'll let you know once I've pushed a new release.

**Comment by thelonious** [comment]
I just pushed v0.5.2 with that fix

**Comment by zowiegong** [comment]
Thanks @thelonious
