### ISSUE TITLE
Is it really required to have node engine limit?

### ISSUE THREAD

**Issue by s0ber** [thelonious/kld-intersections#43]
Hello there! First of all, thanks for the amazing library.

And the question. In my company we have a pretty outdated node version used across the company (v8.16.0), and, while this library actually works under this node, yarn throws an error when trying to install it. I would like to update our node and stuff, but it's not that easy, since infrastructure is huge and it will involve a lot of tedious work of updating dependencies and testing and stuff...

So is it really required to have node v10 for this library to work or is it just a recommendation?

**Comment by thelonious** [comment]
Hi @s0ber,

I can't think of anything specifically needed from v10. I certainly understand your situation with legacy code. I'm back in this code a bit these days. I will try various node versions to see how far back we can go. The main reason this is set to v10 is that is the version I'm developing under and with which I am running tests.

**Comment by s0ber** [comment]
@thelonious I think I've found a temporary solution, so we can close this one. I'll bundle the code in my repo and later, when our infrastructure will be ready, will install it back as a node module.

**Comment by thelonious** [comment]
Thanks @s0ber. Once I get a chance to test other versions, I’ll report back. I can roll back the version to the earliest that works
