### ISSUE TITLE
dependency gp-data-transformer is 404 in npm

### ISSUE THREAD

**Issue by zibiaowu** [thelonious/kld-intersections#51]
when I install your package , the console throw a error " No valid versions available for gp-data-transformer". I found the dependency gp-data-transformer is 404 in npm

![image](https://user-images.githubusercontent.com/18088464/81364595-9bf52b80-9118-11ea-9ce9-b53d3b7b0148.png)

how can I resolve this problem ? Maybe you could provide some replaceable third-party libraries for me ?

**Comment by zibiaowu** [comment]
use 0.7.0 release can solve this problem

**Comment by istvank** [comment]
...but it introduces new problems. :( What a pity it was deleted, I can no longer use 0.6.0.
