### ISSUE TITLE
Fix License Organization Name

### ISSUE THREAD

**Issue by superjag** [thelonious/kld-intersections#61]
Currently there is no organization substituted in the license, causing it to sound like you cannot use your own organization's name to promote itself. Clearly this is not what was intended.

Please fix.

**Comment by thelonious** [comment]
Hello @superjag,

Thanks for point this out.

I've updated the placeholder. I don't know when I'll release a new version, so this is on development only, for the time being. Please re-open if have any other issues with this change.

**Comment by superjag** [comment]
Awesome, thanks.
