### ISSUE TITLE
find all intersections of a path  crossing a group of polygons

### ISSUE THREAD

**Issue by geohuz** [thelonious/kld-intersections#7]
Is it possible to find all intersections of a path (with many segments) which crosses several polygons, the order of the result intersections will be consistent of the path data array? Thanks!

**Comment by thelonious** [comment]
You should be able to find intersections on path segment types, except for maybe arcs. You'll either need to use the DOM to access individual segments in your path, testing each against the polygons, or you can use something like my event-driven path parser to extract the path segments:

- [SVGPathSeg](https://www.w3.org/TR/SVG/paths.html#DOMInterfaces)
- [Path Parser](https://github.com/thelonious/kld-path-parser)

Please note that this code may be too slow for your purposes. There are a number of optimizations that could be used to reduce the number of intersection tests you need to make.
