### ISSUE TITLE
Intersection: this.init is not a function

### ISSUE THREAD

**Issue by arichiardi** [thelonious/kld-intersections#9]
Thank you for this wonderful libray!

I am trying to use the library but I get this error:

```
VM564:2 Uncaught TypeError: this.init is not a function
    at Intersection (<anonymous>:2:10)
    at <anonymous>:1:1
```

It looks like `this` is `window` here and `init` of course is not there.
I checked and this happens on http://www.quazistax.com/testIntersection.html as well.

Do you have any hint for me on how to solve?

EDIT: I am using the release version `0.1.1`.

**Comment by Quazistax** [comment]
Which browser are you using? I encountered other type of problem in Chrome, but that is solved now by adding pathseg.js polyfill to page. I was not able to recreate your type of problem.

**Comment by arichiardi** [comment]
Yes I am using Chrome `Version 55.0.2883.87 (64-bit)`, did you try `Intersection("tets")` in the console?

**Comment by Quazistax** [comment]
try like this
`test = new Intersection("test")`

**Comment by arichiardi** [comment]
Ops Sorry for some reason I was thinking that would work but of course it cannot. Closing!

**Comment by Quazistax** [comment]
No problem :)
